### ISSUE TITLE
J_9 variable starts with lowercase [style guide]

### ISSUE THREAD

**Issue by usgeeus** [tokamak-network/crossTrade#12]
## Configuration
- severity : low
- confidence : medium

## Lines of Codes
```
bytes32 L2HashValue = getHash( …
```
## Description
local variable starts with lowercase

## Recommendation
```
bytes32 l2HashValue = getHash( …
```

**Comment by zzooppii** [comment]
https://github.com/tokamak-network/crossTrade/commit/adbb8622154b7560535bdfe6459859a271947fbc

**Comment by usgeeus** [comment]
Solved, closing this issue.
