### ISSUE TITLE
J_12 use check-effect-interaction pattern [low~medium]

### ISSUE THREAD

**Issue by usgeeus** [tokamak-network/crossTrade#14]
## Configuration
- Severity : low ~ medium
- Confidence : medium

## Description
Even if we don't have a reentry attack issue, this pattern should be widely used.

## Lines of Codes
To all functions
example here
![image](https://github.com/tokamak-network/crossTrade/assets/64007655/1813463b-35de-4c0c-8970-9c8d9cd83ec9)

## Recommendation
example here
Change the location of the external call `sendMessage` and  value assignments to `editEndTime` variables.

# Demo
example here
```
editEndTime[l2HashValue] = block.timestamp + chainData[_l2chainId].editTime;
LL1CroosDomainMessenger(crossDomainMessenger).sendMessage(chainData[_l2chainId].l2fastWithdrawContract, message, _minGasLimit);
```

**Comment by zzooppii** [comment]
https://github.com/tokamak-network/crossTrade/commit/db5a6fe85ee631020658eb1febcb13c6d17a8a13

**Comment by usgeeus** [comment]
Solved, closing this issue.
