### ISSUE TITLE
hash does not contain block.time of FW request from L2 

### ISSUE THREAD

**Issue by suahnkim** [tokamak-network/crossTrade#17]
https://github.com/tokamak-network/crossTrade/blob/2dbfc6b31ac65f3661750f3725d36a9710afd72b/contracts/L1/L1CrossTrade.sol#L155

hash should include block.time of FW request from L2 to minimize effect of L2 reorg (we can catch this error from frontend + contract easily if we add this to hash) 

Alternatively, we can add this check on the frontend code instead.

**Comment by suahnkim** [comment]
above code can be removed as, edit will always honor L1 storage value

**Comment by zzooppii** [comment]
Yes, that's right, the above code will be eliminated by storing fwAmount in L1 as requested and calling another claim function in L2.

**Comment by zzooppii** [comment]
It was decided not to apply block.time to contracts.
