### ISSUE TITLE
J_1. L1FastWithdraw.sol:provideFW [medium]

### ISSUE THREAD

**Issue by zzooppii** [tokamak-network/crossTrade#2]
https://github.com/tokamak-network/L2-FastWithdraw/blob/First_Audit/contracts/L1/L1FastWithdraw.sol#L59
실수로 들어갔거나, 다른 것을 의도하려다가 실수로 넣어진 라인 같습니다. 지우거나 수정이 필요합니다.

**Comment by zzooppii** [comment]
https://github.com/tokamak-network/crossTrade/commit/255aa04e55d47b0f2411a8a6cb778db5788a128b

**Comment by usgeeus** [comment]
Solved, closing this issue.
