### ISSUE TITLE
M_1. [gas optimization]

### ISSUE THREAD

**Issue by MarkInc3** [tokamak-network/crossTrade#3]
## Configuration 
- Severity: low
- Confidence: medium

## Description
There are elements of the main contract that can reduce gas costs.

## Recommendation 
1. If you need to save a little bit of gas, you can use CustomError to do it. (It makes a difference if you use long strings, compare).
https://soliditylang.org/blog/2021/04/21/custom-errors/

2. It seems that it is not possible to upgrade individual functions, i.e. the whole contract must be redeployed when upgrading the logic. If so, it would be possible to save gas and maintain the existing structure by changing the signature value generation to a string and later to an interface format.

## Demo

2. 
``` // 26541 gas 
function encodeWithSignature(address to, uint256 amount) external  returns (bytes memory) {
    // Typo is not checked - "transfer(address, uint)"
    return abi.encodeWithSignature("transfer(address,uint256)", to, amount);
}
// 26526 gas 
function encodeWithSelector(address to, uint256 amount) external  returns (bytes memory) {
    // Type is not checked - (IERC20.transfer.selector, true, amount)
    return abi.encodeWithSelector(IERC20.transfer.selector, to, amount);
}

// 26487 gas
function encodeCall(address to, uint256 amount) external returns (bytes memory) {
    // Typo and type errors will not compile
    return abi.encodeCall(IERC20.transfer, (to, amount));
}

**Comment by zzooppii** [comment]
https://github.com/tokamak-network/crossTrade/commit/785b4be76b5567e035a5480e81a5598826270b10

**Comment by MarkInc3** [comment]
Improvements have been applied.
