### ISSUE TITLE
J_2. Use safeTransfer [high]

### ISSUE THREAD

**Issue by usgeeus** [tokamak-network/crossTrade#4]
## Configuration

- Severity: high
- Confidence: high

## Lines of Code
- L1FastWithdraw.sol:provideFW
- L2FastWithdraw.sol:requestFW
- L2FastWithdraw.sol:claimFW
- L2FastWithdraw.sol:cancelFW

## Description

The return value of an external transfer/transferFrom call is not checked

## Recommendation

1. Use safetransfer function instead of transfer function.

**Comment by zzooppii** [comment]
ae82a1e788c21a2735a760fef6c6954e9a599728

**Comment by usgeeus** [comment]
Solved, closing this issue
