### ISSUE TITLE
Provider condition is checked twice in `claimCT` and `cancelCT`

### ISSUE THREAD

**Issue by parth-15** [tokamak-network/crossTrade#45]
**Describe the bug**
The function `claimCT` and `cancelCT` uses modifier `providerCheck` to ensure that the order is not yet fulfilled. However, in the implementation, same condition is checked again which can result in loss of gas for users.

`providerCheck` modifier
https://github.com/tokamak-network/crossTrade/blob/fc11f6e37f93530a65924f8a89f3487fb2e68ea7/contracts/L2/L2CrossTrade.sol#L61-L64

`claimCT` function
https://github.com/tokamak-network/crossTrade/blob/fc11f6e37f93530a65924f8a89f3487fb2e68ea7/contracts/L2/L2CrossTrade.sol#L189-L204

`cancelCT` function
https://github.com/tokamak-network/crossTrade/blob/fc11f6e37f93530a65924f8a89f3487fb2e68ea7/contracts/L2/L2CrossTrade.sol#L235-L247

**Comment by zzooppii** [comment]
oh thank you
but Someone else left an issue first. https://github.com/tokamak-network/crossTrade/issues/42

**Comment by zzooppii** [comment]
I'll close it.
