### ISSUE TITLE
if-else ladder in provideCT can be optimized

### ISSUE THREAD

**Issue by parth-15** [tokamak-network/crossTrade#47]
**Describe the bug**
There is duplicate logic in if-else ladder in `provideCT` function and can be optimized.

https://github.com/tokamak-network/crossTrade/blob/fc11f6e37f93530a65924f8a89f3487fb2e68ea7/contracts/L1/L1CrossTrade.sol#L87-L106

Optimized code:
```
 if (chainData[_l2chainId].legacyERC20ETH == _l1token) {
            require(msg.value == _fwAmount, "FW: ETH need same amount");
            (bool sent, ) = payable(_to).call{value: msg.value}("");
            require(sent, "claim fail");
   } else {
            _approve(msg.sender, _l1token, _fwAmount);
            IERC20(_l1token).safeTransferFrom(msg.sender, _to, _fwAmount);
        }
```

**Comment by usgeeus** [comment]
_l1token cannot be transfered From msg.sender to _to address directly. This is the case for TON token on Ethereum mainnet,
https://etherscan.io/token/0x2be5e8c109e2197D077D13A82dAead6a9b3433C5#code
If you look at the transferFrom function, there is a conditional check that either the sender or recipient must be msg.sender.

**Comment by zzooppii** [comment]
Yes, it is because of the characteristics of TON tokens.
@usgeeus Thank you

**Comment by zzooppii** [comment]
Please check and close!
