### ISSUE TITLE
J_3 Reentrancy vulnerability [high]

### ISSUE THREAD

**Issue by usgeeus** [tokamak-network/crossTrade#5]
## Configuration
- Severity: High
- Confidence: High

## Lines of Codes
https://github.com/tokamak-network/L2-FastWithdraw/blob/0c94b839742c434147e4b3386f129cb89ab2e124/contracts/L1/L1FastWithdraw.sol#L53-L73

## Description
A state variable is changed after a contract uses call.value.

## Recommendation
1. Apply the [check-effect-interaction pattern.](https://docs.soliditylang.org/en/latest/security-considerations.html#reentrancy)
2. Apply the nonReentrant modifier [developed by Openzepplin ](https://github.com/OpenZeppelin/openzeppelin-contracts/blob/master/contracts/utils/ReentrancyGuardTransient.sol)

## Demo

**Comment by zzooppii** [comment]
https://github.com/tokamak-network/crossTrade/commit/e819a2928a35f2cca7d54c498e00477e8dbcd56a

**Comment by usgeeus** [comment]
The _to parameter of the provideFW function is always an EOA, so we may not need nonReentrant modifier.

I think you can choose one of two things.

1. If you are 100% sure that the _to parameter is always EOA
- you can remove the nonReentrant modifier for gas cost optimization.

2. If you are not sure that the _to parameter is always EOA,
- 
![image](https://github.com/tokamak-network/crossTrade/assets/64007655/d4a24003-2f40-49d8-8bc0-80206b8f7265)
We need to reorder the external calls as shown in the image, because reentry can be done to `cancel` and `edit` functions, and by sending the sendMessage of editFw or cancelFW ahead of claimFW, the provider may be unfairly penalized in L2.
So we need to add the nonReentrant modifier to `cancel` and `edit` as well.

*Regardless of 1 and 2, it looks good to reorder the functions.

**Comment by usgeeus** [comment]
Thanks, closing this issue
