### ISSUE TITLE
for requestRegisteredToken() _totalAmount should not be greater than _ctAmount

### ISSUE THREAD

**Issue by suahnkim** [tokamak-network/crossTrade#55]
https://github.com/tokamak-network/crossTrade/blob/a92ad15c77a551e110ca716b89f510d91c53b549/contracts/L2/L2CrossTrade.sol#L135

add 
require(_totalAmount <=_ctAmount)
for requestRegisteredToken() only. 

This will prevent requester to receive more tokens on L1 than they pay on L2.
For other request functions, we may not want this (if we allow two different tokens to be traded later)

**Comment by zzooppii** [comment]
Will registration only support the same token?

If so, it seems safer to add the require statement you mentioned.

However, if you are conducting transactions like TON -> USDT (or vice versa), you should not register.

**Comment by suahnkim** [comment]
in the future if we support two different tokens, we should create another request function for that. 

the most common usecase should be same token for requestRegisteredToken.

**Comment by zzooppii** [comment]
If you plan to support only same tokens in this version, it seems right to add it.

**Comment by suahnkim** [comment]
if users want to trade two different tokens, they can use non-registered version

**Comment by zzooppii** [comment]
Okay, I understand. I will add the require statement.

**Comment by zzooppii** [comment]
@suahnkim
i added
require(_totalAmount >= _ctAmount, "The totalAmount value must be greater than ctAmount");

It's different from the require you requested, but I added it like this because it seems to be the require statement you wanted. Please check.

**Comment by suahnkim** [comment]
Thank you @zzooppii for checking the logic. much appreciated. (sorry for the mistake)
