### ISSUE TITLE
J_4 onlyEOA modifier [high]

### ISSUE THREAD

**Issue by usgeeus** [tokamak-network/crossTrade#6]
## Configuration
- Severity: high
- Confidence : high

## Lines of Code
https://github.com/tokamak-network/L2-FastWithdraw/blob/aefc050fdaf7c81e1cef3f4a1a5eeea70351b762/contracts/L2/L2FastWithdraw.sol#L194-L196

## Description
onlyEOA modifier can be bypassed if an interacting smart contract has the code written inside its constructor.
[reference](https://solidity-by-example.org/hacks/contract-size/)

## Recommendation
The recommended way to prevent this is to change the onlyEOA() modifier to use require(msg.sender == tx.origin, ".."). This ensures that only EOA address and not contract address, because tx.origin will always refer to the original sender of the transaction which must be an EOA.
```
require(msg.sender == tx.origin)
```

**Comment by zzooppii** [comment]
https://github.com/tokamak-network/crossTrade/commit/aeadfffbd9e48542bb1065035de2272549944b84

**Comment by usgeeus** [comment]
solved closing this issue
