### ISSUE TITLE
J_5. change the way the function return [optimization]

### ISSUE THREAD

**Issue by usgeeus** [tokamak-network/crossTrade#7]
## Configuration
- Severity: low
- Confidence: high

## Lines of Code
https://github.com/tokamak-network/L2-FastWithdraw/blob/aefc050fdaf7c81e1cef3f4a1a5eeea70351b762/contracts/L2/L2FastWithdraw.sol#L178-L190

## Description
You should change the way the function return.

## Recommendation
Since you declared the variable with returns (address l1Token),
you don't need a return statement, just do l1Token = nativeL1token.
Alternatively, you could do something like returns (address) and return nativeL1token;.

**Comment by zzooppii** [comment]
https://github.com/tokamak-network/crossTrade/commit/09aabc0523af9f9c564b736f2a9858926277d7ee

**Comment by usgeeus** [comment]
Solved, closing this issue
