### ISSUE TITLE
J_6. use unchecked [optimization]

### ISSUE THREAD

**Issue by usgeeus** [tokamak-network/crossTrade#8]
## Configuration
- Severity: low
- Confidence: medium

## Lines of Code
https://github.com/tokamak-network/L2-FastWithdraw/blob/aefc050fdaf7c81e1cef3f4a1a5eeea70351b762/contracts/L2/L2FastWithdraw.sol#L73

## Description

unchecked keyword saves gas and allows you to restart from 0 when the count is 2^256.

## Recommendation
```
unchecked {    
        ++ saleCount;    
    }
```

**Comment by zzooppii** [comment]
https://github.com/tokamak-network/crossTrade/commit/3da835e288680cbc6507cd3af1dea72ee87b200a

**Comment by usgeeus** [comment]
Solved, closing this issue.
