### ISSUE TITLE
J_7. add amount check [medium]

### ISSUE THREAD

**Issue by usgeeus** [tokamak-network/crossTrade#9]
## Configuration
- Severity : medium
- Confidence : medium

## Lines of Codes
https://github.com/tokamak-network/L2-FastWithdraw/blob/aefc050fdaf7c81e1cef3f4a1a5eeea70351b762/contracts/L2/L2FastWithdraw.sol#L63-L72

## Description
Should check wether _totalAmount is greator than _fwAmount

## Recommendation
```
require(_totalAmount ≥ _fwAmount)
```

**Comment by zzooppii** [comment]
https://github.com/tokamak-network/crossTrade/commit/40d85a0927aaf40bbe6ec2c34fae8c37dedb0319

**Comment by usgeeus** [comment]
Solved, closing this issue.
